function [P] = bezierHalfConvex(r, s, u, k, b)
    P = { [r 0 0], [r r*s 0], [-r r*s 0], [-r 0 0]; ...
           [(r*u) 0 b], [(r*u) (r*s*u) k], [(-r*u) (r*s*u) k], [(-r*u) 0 b]; ...
           [(r*u) 0 b], [(r*u) -(r*s*u) k], [(-r*u) -(r*s*u) k], [(-r*u) 0 b]; ...
           [r 0 0], [r -r*s 0], [-r -r*s 0], [-r 0 0] 
        };
end
           
